### ISSUE TITLE
Following the mouse

### ISSUE THREAD

**Issue by dmitriitux** [forrestkirby/image-comparison-element#2]
Hi, as far as I understand, you can only compare by clicking on the mouse. Can a slider be made to run after the mouse?

**Comment by forrestkirby** [comment]
Hi dmitriitux,

sorry for the late reply, I didn’t receive a notification when the issue was created. You are right, the slider position only changes when you click on or touch the element. What you are asking for is not a feature of this element. It can probably achieved with custom JavaScript checking the pointer position on every move, though.

Best regards
Thomas

**Comment by dmitriitux** [comment]
@forrestkirby sorry for the curse that I wrote :) I did not immediately notice that the translator brought it out.
Will you add to this item? Yes, it's just add javascript to it on the mousemove event

**Comment by forrestkirby** [comment]
> sorry for the curse that I wrote

Nevermind, I thought that this was a typo anyway.

> Will you add to this item?

No, I don’t think so at the moment.

**Comment by AlixanTelnov** [comment]
If you support us and agree to add the ability to track the mouse without clicking, it will make your module even better!))

Thank you for your module, I make websites for clinics, and your module is irreplaceable! I really ask you to modify its response to the movement of the mouse)

**Comment by forrestkirby** [comment]
Please try branch [2.3.27](https://github.com/forrestkirby/image-comparison-element/tree/2.3.27) in which an option for this has been added.

**Comment by AlixanTelnov** [comment]
It's just great!
Sell it to customers, I would like to pay for a great job!
